#!/bin/sh

DION_HOME="$HOME/private/dion"
DION_VERSION="0.1.0-SNAPSHOT-standalone"
DIONJAR="$DION_HOME/target/uberjar/dion-$DION_VERSION.jar"


if [ -f "${JAVA_HOME}/bin/java" ]; then
	JAVA=${JAVA_HOME}/bin/java
else
	JAVA=java
fi
export JAVA

STARTARGS="--verbose start"

# Execute Java
exec $JAVA -jar $DIONJAR $@ 
